const { test, expect } = require('@jest/globals')
const correctA2 = require('../Functionality/QuestionsAndAnswers2')

test('correctA2 should return the correct answer for the question being passed in', () => 
{
    expect(correctA2("What arithmetic operator calculates the remainder of its two operands?")).toBe("%")
    expect(correctA2("What arithmetic operator calculates the quotient of its two operands?")).toBe("/")
    expect(correctA2('What arithmetic operator calculates the product of its two operands?')).toBe('*')
    expect(correctA2('What arithmetic operator calculates the difference of its two operands?')).toBe('-')
    expect(correctA2('What arithmetic operator calculates the sum of its two operands?')).toBe('+')
    expect(correctA2('What is a shorthand way to compute x=x+1?')).toBe('x+=1')
    expect(correctA2('What is a shorthand way to compute x=x-1?')).toBe('x-=1')
    expect(correctA2('What is a shorthand way to compute x=x*1?')).toBe('x*=1')
    expect(correctA2('What is a shorthand way to compute x=x/1?')).toBe('x/=1')
    expect(correctA2('What is a shorthand way to compute x=x%1?')).toBe('x%=1')
    expect(correctA2('How do you force specific operations to be performed before others in a mathematical expression?')).toBe('(   )')
    expect(correctA2("Which is a prefix incrementation of var?")).toBe("++var")
    expect(correctA2("Which is a postfix incrementation of var?")).toBe("var++")
    expect(correctA2("What is a shorthand way to compute var=var+5?")).toBe("var+=5")
})